#include "homepi/usb-devices/artifact-writer.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>

namespace fs = std::filesystem;

namespace homepi::usb_devices {

namespace {

/**
 * Ensures a directory exists.
 * @param path Directory path.
 */
void ensure_dir(const fs::path& path) {
  std::error_code ec;
  fs::create_directories(path, ec);
}

/**
 * Finds a device by id.
 * @param devices Device list.
 * @param device_id Target id.
 * @return Pointer to device or nullptr.
 */
const UsbDevice* find_device(const std::vector<UsbDevice>& devices, const std::string& device_id) {
  for (const UsbDevice& device : devices) {
    if (device.device_id == device_id) {
      return &device;
    }
  }
  return nullptr;
}

}  // namespace

ArtifactWriter::ArtifactWriter(const ServiceConfig& config) : config_(config) {}

bool ArtifactWriter::regenerate(const UsbAssignments& assignments,
                                const std::vector<UsbDevice>& devices) {
  const fs::path generated(config_.generated_dir);
  ensure_dir(generated / "udev");
  ensure_dir(generated / "alsa");
  ensure_dir(generated / "modprobe");

  std::ostringstream udev;
  udev << "# Generated by homepi-usb-devices — do not edit\n";

  if (assignments.serial && !assignments.serial->empty()) {
    if (const UsbDevice* device = find_device(devices, *assignments.serial)) {
      udev << "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"" << device->id_vendor
           << "\", ATTRS{idProduct}==\"" << device->id_product << "\"";
      if (!device->serial.empty()) {
        udev << ", ATTRS{serial}==\"" << device->serial << "\"";
      }
      udev << ", SYMLINK+=\"" << config_.serial_symlink << "\"\n";
    }
  }

  const fs::path udev_path = generated / config_.udev_rules_relative;
  ensure_dir(udev_path.parent_path());
  {
    std::ofstream out(udev_path);
    out << udev.str();
  }

  const std::string stable_primary_hw =
      "hw:" + config_.primary_audio_alsa_id + ",0";

  {
    const fs::path modprobe_path = generated / config_.modprobe_relative;
    ensure_dir(modprobe_path.parent_path());
    std::ofstream out(modprobe_path);
    out << "# Generated by homepi-usb-devices — do not edit\n";
    out << "# Replug primary USB DAC or reboot after changing Primary Audio Output.\n";
    if (!assignments.audio_primary || assignments.audio_primary->empty()) {
      out << "# No primary audio assignment\n";
    } else if (const UsbDevice* device = find_device(devices, *assignments.audio_primary)) {
      if (device->id_vendor.empty() || device->id_product.empty()) {
        out << "# Primary device missing USB vendor/product identity\n";
      } else {
        out << "options snd-usb-audio id=" << config_.primary_audio_alsa_id << " vid=0x"
            << device->id_vendor << " pid=0x" << device->id_product << " enable=1\n";
      }
    } else {
      out << "# Assigned primary device not found in inventory\n";
    }
  }

  auto write_alsa = [&](const char* filename, const char* pcm_name,
                        const std::optional<std::string>& device_id, bool use_stable_primary) {
    const fs::path path = generated / "alsa" / filename;
    std::ofstream out(path);
    if (!device_id || device_id->empty()) {
      out << "# No assignment for " << pcm_name << "\n";
      return;
    }
    if (use_stable_primary) {
      out << "pcm." << pcm_name << " {\n"
          << "  type plug\n"
          << "  slave.pcm \"" << stable_primary_hw << "\"\n"
          << "}\n";
      return;
    }
    const UsbDevice* device = find_device(devices, *device_id);
    if (device == nullptr || device->resolved_alsa_name.empty()) {
      out << "# Assigned device missing ALSA mapping\n";
      return;
    }
    out << "pcm." << pcm_name << " {\n"
        << "  type plug\n"
        << "  slave.pcm \"" << device->resolved_alsa_name << "\"\n"
        << "}\n";
  };

  write_alsa("10-homepi-audio-out.conf", "AudioOut", assignments.audio_primary, true);
  write_alsa("20-homepi-audio-paging.conf", "AudioPaging", assignments.paging, false);

  return true;
}

}  // namespace homepi::usb_devices
