#pragma once

#include <functional>
#include <string>

namespace homepi::audio_paging {

/** Lazy ALSA playback wrapper that shells out to aplay for paging DAC output. */
class PcmPlayer {
 public:
  /** Creates player bound to ALSA playback device (plug:AudioPaging required). */
  explicit PcmPlayer(std::string alsa_device);

  /** Sets ALSA card index used to normalize hardware DAC output volume. */
  void set_alsa_card_index(int card_index);

  /** Plays signed 16-bit mono raw PCM generated by Piper. */
  bool play_raw_file(const std::string& raw_path, int sample_rate_hz);

  /** Plays a wav file via aplay (used by chimes). */
  bool play_wav_file(const std::string& wav_path);

  /** Returns true while playback process is active. */
  bool is_open() const;

  /** Sets callbacks fired when playback opens/closes the DAC. */
  void set_state_callbacks(std::function<void()> on_open, std::function<void()> on_close);

 private:
  bool run_aplay(const std::string& command);

  std::string alsa_device_;
  int alsa_card_index_ = -1;
  bool open_ = false;
  std::function<void()> on_open_;
  std::function<void()> on_close_;
};

}  // namespace homepi::audio_paging
