CREATE TABLE IF NOT EXISTS contact_sensor_controllers (
  controller_id TEXT PRIMARY KEY,
  controller_type TEXT NOT NULL,
  controller_model TEXT NOT NULL,
  i2c_bus TEXT,
  i2c_address TEXT,
  inta_net_name TEXT,
  inta_pi_physical_pin INTEGER,
  inta_bcm_gpio INTEGER,
  intb_net_name TEXT,
  intb_pi_physical_pin INTEGER,
  intb_bcm_gpio INTEGER,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (controller_type IN ('mcp23017', 'raspberry_pi_gpio'))
);

CREATE TABLE IF NOT EXISTS contact_sensors (
  sensor_id TEXT PRIMARY KEY,
  sensor_number INTEGER NOT NULL UNIQUE,
  sensor_name TEXT NOT NULL,
  sensor_type TEXT NOT NULL DEFAULT 'other',
  room_id TEXT,
  room_name TEXT,
  controller_id TEXT NOT NULL,
  hardware_type TEXT NOT NULL,
  hardware_model TEXT NOT NULL,
  schematic_net_name TEXT,
  i2c_address TEXT,
  mcp_bank TEXT,
  mcp_pin INTEGER,
  pi_physical_pin INTEGER,
  bcm_gpio INTEGER,
  gpio_chip TEXT,
  gpio_line INTEGER,
  invert_logic INTEGER NOT NULL DEFAULT 0,
  debounce_ms INTEGER NOT NULL DEFAULT 50,
  homekit_enabled INTEGER NOT NULL DEFAULT 0,
  homekit_accessory_uuid TEXT,
  contact_state TEXT NOT NULL DEFAULT 'unknown',
  raw_value INTEGER,
  faulted INTEGER NOT NULL DEFAULT 0,
  fault_reason TEXT,
  tamper_supported INTEGER NOT NULL DEFAULT 0,
  tampered INTEGER NOT NULL DEFAULT 0,
  tamper_reason TEXT,
  last_changed_at TEXT,
  last_seen_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (sensor_type IN ('door', 'window', 'other')),
  CHECK (hardware_type IN ('mcp23017', 'raspberry_pi_gpio')),
  CHECK (hardware_model IN ('MCP1', 'MCP2', 'Raspberry Pi')),
  CHECK (contact_state IN ('open', 'closed', 'unknown')),
  FOREIGN KEY (controller_id) REFERENCES contact_sensor_controllers(controller_id)
);
