#!/usr/bin/env bash
set -euo pipefail

GENERATED_ALSA_DIR="${HOMEPI_GENERATED_ALSA_DIR:-/opt/homepi/runtime/generated/alsa}"
TARGET_ASOUNDRC="${HOMEPI_USER_ASOUNDRC:-/home/homepi/.asoundrc}"

if [[ ! -d "${GENERATED_ALSA_DIR}" ]]; then
  echo "Generated ALSA directory not found: ${GENERATED_ALSA_DIR}" >&2
  exit 1
fi

mapfile -t SNIPPETS < <(find "${GENERATED_ALSA_DIR}" -maxdepth 1 -name '*.conf' -type f | sort)
if [[ "${#SNIPPETS[@]}" -eq 0 ]]; then
  echo "No ALSA snippet files found in ${GENERATED_ALSA_DIR}" >&2
  exit 1
fi

{
  echo "# Generated by homepi-audio-paging — do not edit"
  echo "# Source: ${GENERATED_ALSA_DIR}"
  for snippet in "${SNIPPETS[@]}"; do
    echo "# --- $(basename "${snippet}") ---"
    cat "${snippet}"
    echo
  done
} > "${TARGET_ASOUNDRC}.tmp"

mv "${TARGET_ASOUNDRC}.tmp" "${TARGET_ASOUNDRC}"
chown homepi:homepi "${TARGET_ASOUNDRC}" 2>/dev/null || true
echo "Synced ALSA user config to ${TARGET_ASOUNDRC}"
