-- HomePi audio paging schema (homepi-audio-paging service)

CREATE TABLE IF NOT EXISTS AUDIO_PAGING_CONFIG (
  ID INTEGER PRIMARY KEY CHECK (ID = 1),
  ENABLED INTEGER NOT NULL DEFAULT 0,
  DEFAULT_VOICE_ID TEXT,
  ACTIVE_VOICE_ID TEXT,
  ACTIVE_CHIME_ID TEXT NOT NULL DEFAULT 'default',
  MAX_INSTALLED_VOICES INTEGER NOT NULL DEFAULT 2,
  MAX_TEXT_LENGTH INTEGER NOT NULL DEFAULT 4000,
  MAX_PREVIEW_TEXT_LENGTH INTEGER NOT NULL DEFAULT 120,
  STREAM_THRESHOLD_CHARS INTEGER NOT NULL DEFAULT 200,
  MIN_PREROLL_MS INTEGER NOT NULL DEFAULT 100,
  DEFAULT_ON_BUSY TEXT NOT NULL DEFAULT 'reject',
  IDLE_POLICY TEXT NOT NULL DEFAULT 'always_warm',
  IDLE_WARM_TIMEOUT_MS INTEGER NOT NULL DEFAULT 1800000,
  DAC_IDLE_CLOSE_DELAY_MS INTEGER NOT NULL DEFAULT 3000,
  KEEP_LAST_AUDIO_FOR_DEBUG INTEGER NOT NULL DEFAULT 0,
  CREATED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIO_PAGING_VOICES (
  VOICE_ID TEXT PRIMARY KEY,
  DISPLAY_NAME TEXT NOT NULL,
  LANGUAGE_CODE TEXT NOT NULL,
  QUALITY TEXT,
  MODEL_PATH TEXT NOT NULL,
  CONFIG_PATH TEXT NOT NULL,
  INSTALLED INTEGER NOT NULL DEFAULT 1,
  IS_DEFAULT INTEGER NOT NULL DEFAULT 0,
  IS_BUNDLED INTEGER NOT NULL DEFAULT 0,
  LAST_USED_AT TEXT,
  CREATED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIO_PAGING_CHIMES (
  CHIME_ID TEXT PRIMARY KEY,
  DISPLAY_NAME TEXT NOT NULL,
  FILE_PATH TEXT NOT NULL,
  DURATION_MS INTEGER,
  IS_DEFAULT INTEGER NOT NULL DEFAULT 0,
  IS_BUNDLED INTEGER NOT NULL DEFAULT 0,
  CREATED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIO_PAGING_API_KEY (
  ID INTEGER PRIMARY KEY CHECK (ID = 1),
  KEY_HASH TEXT NOT NULL,
  KEY_PREFIX TEXT NOT NULL,
  CREATED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIO_PAGING_JOBS (
  JOB_ID TEXT PRIMARY KEY,
  CORRELATION_ID TEXT NOT NULL,
  STATUS TEXT NOT NULL,
  SOURCE TEXT NOT NULL,
  JOB_TYPE TEXT NOT NULL DEFAULT 'speak',
  TEXT_HASH TEXT,
  TEXT_LENGTH INTEGER,
  VOICE_ID TEXT,
  CHIME_ID TEXT,
  INCLUDE_CHIME INTEGER NOT NULL DEFAULT 0,
  REQUESTED_AT TEXT NOT NULL,
  STARTED_AT TEXT,
  PAGE_ON_AT TEXT,
  PLAYBACK_STARTED_AT TEXT,
  PLAYBACK_COMPLETED_AT TEXT,
  COMPLETED_AT TEXT,
  ERROR_STAGE TEXT,
  ERROR_MESSAGE TEXT,
  CREATED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL
);

INSERT OR IGNORE INTO AUDIO_PAGING_CONFIG (
  ID, ENABLED, DEFAULT_VOICE_ID, ACTIVE_VOICE_ID, ACTIVE_CHIME_ID, MAX_INSTALLED_VOICES,
  MAX_TEXT_LENGTH, MAX_PREVIEW_TEXT_LENGTH, STREAM_THRESHOLD_CHARS, MIN_PREROLL_MS,
  DEFAULT_ON_BUSY, IDLE_POLICY, IDLE_WARM_TIMEOUT_MS, DAC_IDLE_CLOSE_DELAY_MS,
  KEEP_LAST_AUDIO_FOR_DEBUG, CREATED_AT, UPDATED_AT
) VALUES (
  1, 0, 'en_US-lessac-medium', 'en_US-lessac-medium', 'default', 2,
  4000, 120, 200, 100,
  'reject', 'always_warm', 1800000, 3000,
  0, datetime('now'), datetime('now')
);

INSERT OR IGNORE INTO AUDIO_PAGING_VOICES (
  VOICE_ID, DISPLAY_NAME, LANGUAGE_CODE, QUALITY, MODEL_PATH, CONFIG_PATH,
  INSTALLED, IS_DEFAULT, IS_BUNDLED, LAST_USED_AT, CREATED_AT, UPDATED_AT
) VALUES (
  'en_US-lessac-medium', 'Lessac', 'en-US', 'medium',
  '/var/lib/homepi/paging/voices/en_US-lessac-medium.onnx',
  '/var/lib/homepi/paging/voices/en_US-lessac-medium.onnx.json',
  1, 1, 1, datetime('now'), datetime('now'), datetime('now')
);

INSERT OR IGNORE INTO AUDIO_PAGING_CHIMES (
  CHIME_ID, DISPLAY_NAME, FILE_PATH, DURATION_MS, IS_DEFAULT, IS_BUNDLED, CREATED_AT, UPDATED_AT
) VALUES (
  'default', 'Default', '/var/lib/homepi/paging/chimes/default.wav', 250, 1, 1, datetime('now'),
  datetime('now')
);
